name: Deploy to AWS with Terragrunt

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Apply Terragrunt
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: "1.9.8"
          tg_version: "0.69.1"
          tg_dir: "prod/us-east-1"
          tg_command: "run-all apply --terragrunt-non-interactive -auto-approve"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
